# Chapter 2 - Vectors, Matrices, and Multidimensional Arrays

When a computation must be repeated for a set of input values, it is natural and advantageous to represent the data as arrays and the computation in terms of array operations.

Computations that are formulated this way are said to be **vectorized**.

Vetorized computing eliminates the need for many explicit loops over the array elements by applying batch operations on the array data.

In Python scientific computing environment, efficient data structures for working with arrays are provided by the NumPy library. The core of NumPy is implemented in C and provides efficient functions for manipulating and processing arrays.

NumPy arrays are **homogenous and typed arrays of fixed size** and Python lists are generic containers of objects.

### Importing the modules

In [1]:
import numpy as np

The core of the Numpy is the data structures for representing multidimentsional arrays of **homogenous data**. Homogenous referes to all elements in an array having the same data type.

#### Basic attributes of the ndarray Class

- Shape: tuple that contains the number of elements for each dimension(axis)
- Size: total number elements
- Ndim: Number of dimensions (axes)
- nbytes: Number of bytes used to store data
- dtype: data type of the elements in the array (remember: **Homogenous**)

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.nbytes

48

In [9]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)

In [10]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [11]:
(d1 + d2).dtype

dtype('complex128')

#### Real and Imaginary Parts

Numpy array instances have the attribute **real** and **imag** for extracting the real and imaginary parts of the array, respectively

In [12]:
data = np.array([1, 2, 3], dtype=complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
data.real

array([1., 2., 3.])

In [14]:
data.imag

array([0., 0., 0.])

### Order of Array Data in Memory

Arrays are stored as contiguous data in memory. There is a freedom of choise in how to arrange the array elements in this memory segment.

For example, a two-dimensional array, containing rows and columns: one possible way to store this array as consecutive sequence of values is store the rows after each other, or store the columns one after another.

NumPy array can be specifed to be stored in a row-major format, using the keyword **order = 'F'**, and column-major format, using the keyword **order = 'C'**. The default format is row-major ( 'F' )

The F and C ordering of Numpy array is particularly relevant when NumPy arrays are used in interfaces with software written in C and Fortran, which is often required when working with numerical computing with Python.

The NumPy attribute **ndarray.strides** defines exactly how this mapping is done. The attribute is a tuple of the same length as the number of axes (dimensions) of the array. Each value in strides is the factor by which the index for the corresponfing axis is multiplied when calculating the memory offsed (in bytes).

For example, consider a C-order array A with shape (2, 3), which corresponds to a two-dimensional array with two and three elements along the first and the second dimensions, respectively. If the *datatype is int32*, each element uses *4 bytes*, and the total memory buffer for the array uses *2 x 3 x 4 = 24 bytes*. The *strides* attribute of this array is therefore (4 x 3, 4 x 1) = (12, 4).

### Arrays with Constant Values

The functions **np.zeros** and **np.ones** create and return arrays filled with zeros and ones.

They take, as first argument, an integer or a typle that describes the number of elements along each dimension of the array.

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
data = np.ones((2, 3))
data.dtype

dtype('float64')

In [18]:
data = np.ones((2, 3), dtype=np.int64)
data.dtype

dtype('int64')

An array filled with an arbitrary constant value can be generated by first creating an array filled with ones and then multiplying the array with the desired fill value.

But, NumPy provides the function **np.full** that does exactly this in one step

In [19]:
x1 = 5.4 * np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [20]:
x1 = np.full(10, 5.4)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [21]:
x1 = np.empty(5)
x1

array([0., 0., 0., 0., 0.])

In [22]:
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

### Arrays with Incremental Sequences

In numerical computing its very common to require arrays with incremental values between a starting value and ending value. NumPy provides two similar functions to create such arrays: **np.arange** and **np.linspace**. 

Both functions take three arguments, the first two are the start and end values. The third argument of **np.arange** is the increment, while for **np.linspace** is the total element numbers in the array.

In [23]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
np.linspace(0.0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.linspace(0.0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [26]:
np.arange(0.0, 10, .001)

array([0.000e+00, 1.000e-03, 2.000e-03, ..., 9.997e+00, 9.998e+00,
       9.999e+00])

### Arrays with Logarithmic Sequences

The function **np.logspace** is similar to **np.linspace** but the first two arguments are the powers of the optional base argument(which defaults to 10(.

For example, to generate an array with logarithmically distributed values between 1 and 100, we can use:

In [27]:
np.logspace(0, 2, 5) # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [28]:
np.logspace(0, 2, 3) # 10**0, 10**1, 10**2

array([  1.,  10., 100.])

### Meshgrid Arrays

Multidimensional coordinate grids can be generated using the function **np.meshgrid**.

Given two one-dimensional coordinate arrays, we can generate two-dimensional coordinate arrays using the **np.meshgrid** function. 

In [29]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [30]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

### Uninitialized Arrays

The function **np.empty** creates a array without initializing the elements.

The advantage is, for example, instead of **np.zeros**, which creates a array initialized with zero-valued elements, is that we can avoid the initilization step. 
If all the elements are initialized later in the code, this can save a little bit of time, especially when working with large arrays.

In [31]:
np.empty(3, dtype=np.float)

array([  1.,  10., 100.])

If performance gain is not essential, maybe is better use **np.zeros**.

### Arrays with Properties of other Arrays

To create new arrays that share properties, such as shape and data type, we can use **np.ones_like, np.zeros_like, np.full_like**, and **np.empty_like**.

A typical use-case is when requires working with arrays of the same size and type

In [32]:
def f(x):
    y = np.ones_like(x)
    return x - y

f(np.zeros((5, 5)))

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

### Creating Matrix Arrays

Matrices, or two-dimensional arrays, are important in numerical computing. NumPy provides functions for generating commnly used matrices. For example, **np.identity** generates a square matrix with ones on the diagonal and zeros elsewhere.

In [33]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**np.eye** generates identity matrices with optionally offset

In [34]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.eye(10, k=1)

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.eye(10, k=-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

to construct a arbritrary one-dimensional array on the diagonal, we can use **np.diag** function

In [37]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

**np.diag** have *k* argument

In [38]:
np.diag(np.arange(0, 40, 5), k=1)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 15,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 20,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 25,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 30,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 35],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

## Indexing and Slicing

Elements and subarrays are accessed using the standart **quare bracket** notation that is also used with Python lists.

### One-Dimensional Arrays

In [41]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
a[0] # first element

0

In [48]:
a[-1] # last element

10

In [49]:
a[-2]

9

In [50]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

### Multidimensional Arrays

With multidimensional arrays, element selections likethose introduced in the previous section can be applied on each axis (dimension). The result is a reduced array where each elememt matches the given selection rules.

In [52]:
f = lambda m, n: n + 10 * m

In [56]:
np.fromfunction?

Signature: np.fromfunction(function, shape, **kwargs)
Docstring:
Construct an array by executing a function over each coordinate.

The resulting array therefore has a value ``fn(x, y, z)`` at
coordinate ``(x, y, z)``.

Parameters
----------
function : callable
    The function is called with N parameters, where N is the rank of
    `shape`.  Each parameter represents the coordinates of the array
    varying along a specific axis.  For example, if `shape`
    were ``(2, 2)``, then the parameters would be
    ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
shape : (N,) tuple of ints
    Shape of the output array, which also determines the shape of
    the coordinate arrays passed to `function`.
dtype : data-type, optional
    Data-type of the coordinate arrays passed to `function`.
    By default, `dtype` is float.

Returns
-------
fromfunction : any
    The result of the call to `function` is passed back directly.
    Therefore the shape of `fromfunction` is completely deter

In [54]:
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [57]:
A[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [58]:
A[1:-1, 1:-1]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [59]:
A[:, 1] # second column

array([ 1, 11, 21, 31, 41, 51])

In [60]:
A[:3, :3] # upper half

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [63]:
A[3:, 3:] # lower

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

### Views

Subarrays that are extarcted from arrays usaing slices operations are alternative views of the same underlying array data.

**They are arrays that refer to the same data in the memory as the original array.**

In [65]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [67]:
B[:, :] = 0
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

When a copy rather than a view is needed, the view can be copied explicitly by using the **copy** method of the ndarray instance.

In [70]:
C = B[1:3, 1:3].copy()
C

array([[0, 0],
       [0, 0]])

In [71]:
C[:, :] = 1

In [72]:
C

array([[1, 1],
       [1, 1]])

In [73]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Fancy Indexing and Boolean-Valued Indexing

NumPy provides another convenient method to index arrays, called fancy indexing.

With fancy indexing, an array can be indexed with another NumPy array, a Python list, or a sequence of integers, whose values select elements in the indexed array.

**Unlike arrays created using slices, the arrays returned using fancy indexing and Boolean-valued indexing are not views but rather new independent arrays.**

In [75]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [79]:
A[np.array([0, 2, 4])] # indexing with numpy list

array([0. , 0.2, 0.4])

In [78]:
A[[0, 2, 4]] # indexing with python list

array([0. , 0.2, 0.4])

In [80]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [82]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

## Reshaping and Resizing

When working with data in array form, it is often useful to rearrange and alter the way they are interpreted.

In [85]:
data = np.array([[1,2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [86]:
data.reshape((1, 4))

array([[1, 2, 3, 4]])

In [88]:
data.reshape(1, 4)

array([[1, 2, 3, 4]])

In [87]:
data.reshape(4)

array([1, 2, 3, 4])

In [89]:
data

array([[1, 2],
       [3, 4]])

In [90]:
data.flatten()

array([1, 2, 3, 4])

In [92]:
data.flatten().shape

(4,)

While **np.flatten** collapse the axes of an array into a one-dimensional array, it is also possible to introduce new axes into an array, either using **np.reshape** or, when adding new empty axes, using indexing notation and the **np.newaxis** keyword at the place of a new axis.

In [114]:
data = np.arange(0, 5)
data

array([0, 1, 2, 3, 4])

In [108]:
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [109]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])