# Chapter 2 - Vectors, Matrices, and Multidimensional Arrays

When a computation must be repeated for a set of input values, it is natural and advantageous to represent the data as arrays and the computation in terms of array operations.

Computations that are formulated this way are said to be **vectorized**.

Vetorized computing eliminates the need for many explicit loops over the array elements by applying batch operations on the array data.

In Python scientific computing environment, efficient data structures for working with arrays are provided by the NumPy library. The core of NumPy is implemented in C and provides efficient functions for manipulating and processing arrays.

NumPy arrays are **homogenous and typed arrays of fixed size** and Python lists are generic containers of objects.

### Importing the modules

In [1]:
import numpy as np

The core of the Numpy is the data structures for representing multidimentsional arrays of **homogenous data**. Homogenous referes to all elements in an array having the same data type.

#### Basic attributes of the ndarray Class

- Shape: tuple that contains the number of elements for each dimension(axis)
- Size: total number elements
- Ndim: Number of dimensions (axes)
- nbytes: Number of bytes used to store data
- dtype: data type of the elements in the array (remember: **Homogenous**)

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.nbytes

48

In [9]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)

In [10]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [11]:
(d1 + d2).dtype

dtype('complex128')

#### Real and Imaginary Parts

Numpy array instances have the attribute **real** and **imag** for extracting the real and imaginary parts of the array, respectively

In [12]:
data = np.array([1, 2, 3], dtype=complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
data.real

array([1., 2., 3.])

In [14]:
data.imag

array([0., 0., 0.])

### Order of Array Data in Memory

Arrays are stored as contiguous data in memory. There is a freedom of choise in how to arrange the array elements in this memory segment.

For example, a two-dimensional array, containing rows and columns: one possible way to store this array as consecutive sequence of values is store the rows after each other, or store the columns one after another.

NumPy array can be specifed to be stored in a row-major format, using the keyword **order = 'F'**, and column-major format, using the keyword **order = 'C'**. The default format is row-major ( 'F' )

The F and C ordering of Numpy array is particularly relevant when NumPy arrays are used in interfaces with software written in C and Fortran, which is often required when working with numerical computing with Python.

The NumPy attribute **ndarray.strides** defines exactly how this mapping is done. The attribute is a tuple of the same length as the number of axes (dimensions) of the array. Each value in strides is the factor by which the index for the corresponfing axis is multiplied when calculating the memory offsed (in bytes).

For example, consider a C-order array A with shape (2, 3), which corresponds to a two-dimensional array with two and three elements along the first and the second dimensions, respectively. If the *datatype is int32*, each element uses *4 bytes*, and the total memory buffer for the array uses *2 x 3 x 4 = 24 bytes*. The *strides* attribute of this array is therefore (4 x 3, 4 x 1) = (12, 4).

### Arrays with Constant Values

The functions **np.zeros** and **np.ones** create and return arrays filled with zeros and ones.

They take, as first argument, an integer or a typle that describes the number of elements along each dimension of the array.

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
data = np.ones((2, 3))
data.dtype

dtype('float64')

In [18]:
data = np.ones((2, 3), dtype=np.int64)
data.dtype

dtype('int64')

An array filled with an arbitrary constant value can be generated by first creating an array filled with ones and then multiplying the array with the desired fill value.

But, NumPy provides the function **np.full** that does exactly this in one step

In [19]:
x1 = 5.4 * np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [20]:
x1 = np.full(10, 5.4)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [21]:
x1 = np.empty(5)
x1

array([-3.10503618e+231, -3.10503618e+231, -3.10503618e+231,
       -3.10503618e+231, -3.10503618e+231])

In [22]:
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

### Arrays with Incremental Sequences

In numerical computing its very common to require arrays with incremental values between a starting value and ending value. NumPy provides two similar functions to create such arrays: **np.arange** and **np.linspace**. 

Both functions take three arguments, the first two are the start and end values. The third argument of **np.arange** is the increment, while for **np.linspace** is the total element numbers in the array.

In [29]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
np.linspace(0.0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
np.linspace(0.0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [36]:
np.arange(0.0, 10, .001)

array([0.000e+00, 1.000e-03, 2.000e-03, ..., 9.997e+00, 9.998e+00,
       9.999e+00])

### Arrays with Logarithmic Sequences

The function **np.logspace** is similar to **np.linspace** but the first two arguments are the powers of the optional base argument(which defaults to 10(.

For example, to generate an array with logarithmically distributed values between 1 and 100, we can use:

In [38]:
np.logspace(0, 2, 5) # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [46]:
np.logspace(0, 2, 3) # 10**0, 10**1, 10**2

array([  1.,  10., 100.])

### Meshgrid Arrays

Multidimensional coordinate grids can be generated using the function **np.meshgrid**.

Given two one-dimensional coordinate arrays, we can generate two-dimensional coordinate arrays using the **np.meshgrid** function. 

In [48]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [49]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])